import os
import logging
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from core.activity_tracker import tracker

last_file = None

# Common code file extensions to track
CODE_EXTENSIONS = {'.py', '.js', '.ts', '.java', '.c', '.cpp', '.h', '.cs', '.go',
                   '.rb', '.php', '.html', '.css', '.json', '.xml', '.yaml', '.yml',
                   '.md', '.txt', '.sql', '.sh', '.bat', '.ps1', '.r', '.swift', '.kt'}

class ChangeHandler(FileSystemEventHandler):
    """Handles file system events generated by Watchdog."""
    def on_modified(self, event):
        global last_file
        
        if not event.is_directory:
            src = event.src_path
            
            # Aggressively ignore system and background folders
            skip_dirs = [
                "\\.git\\", "\\__pycache__\\", "\\node_modules\\", 
                "\\AppData\\", "\\Windows\\", "\\ProgramData\\", 
                "\\Program Files\\", "\\Program Files (x86)\\", 
                "\\Temp\\", "\\OEM\\"
            ]
            if any(skip.lower() in src.lower() for skip in skip_dirs):
                return
                
            _, ext = os.path.splitext(src)
            if ext.lower() in CODE_EXTENSIONS:
                last_file = os.path.abspath(src)
                logging.info(f"File change detected: {last_file}")
                # Feed into activity tracker
                tracker.add_file_event(last_file)

def start_file_monitor(path=None) -> list[Observer]:
    """Start tracking file modifications across all major drives."""
    observers = []
    
    # If no specific path given, monitor root drives
    paths_to_watch = [path] if path else []
    
    if not paths_to_watch:
        # Check standard Windows drives
        for drive in ['C:\\', 'D:\\', 'E:\\', 'F:\\']:
            if os.path.exists(drive):
                paths_to_watch.append(drive)
        
        # Fallback if somehow no drives found
        if not paths_to_watch:
            paths_to_watch.append(os.path.expanduser("~"))
            
    for watch_path in paths_to_watch:
        try:
            observer = Observer()
            handler = ChangeHandler()
            observer.schedule(handler, watch_path, recursive=True)
            observer.start()
            observers.append(observer)
            logging.info(f"File monitor started on {watch_path}")
        except Exception as e:
            logging.warning(f"Could not start file monitor on {watch_path}: {e}")
            
    return observers

def get_last_modified_file() -> str:
    """Return the path of the last recorded modified file."""
    return last_file or "None"
